// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	createCaseSession: (id: string, templateId: string) => __TAURI_INVOKE<CaseSession>("create_case_session", { id, templateId }),
	extractRawText: (text: string) => typedError<ExtractedBlock, IngestError>(__TAURI_INVOKE("extract_raw_text", { text })),
	extractTextFile: (fileName: string, bytes: number[]) => typedError<ExtractedBlock, IngestError>(__TAURI_INVOKE("extract_text_file", { fileName, bytes })),
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
};

/* Types */
export type CaseSession = {
	id: string,
	template_id: string,
	inputs: ExtractedBlock[],
	current_output: string | null,
	reviewed_output_hash: string | null,
};

export type ExtractedBlock = {
	id: string,
	round: number,
	provenance: InputProvenance,
	content: string,
};

export type IngestError = { key: "empty_input" } | { key: "invalid_utf8" } | { key: "unsupported_binary"; mime: string } | { key: "unsupported_control_characters" };

export type InputProvenance = "RawText" | ({ File: {
	name: string,
} }) & { Url?: never } | "Clipboard" | ({ Url: {
	address: string,
} }) & { File?: never };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

