// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
  cancelGeneration: (requestId: string) =>
    typedError<boolean, LlmError>(__TAURI_INVOKE("cancel_generation", { requestId })),
  clearCaseSession: (caseId: string) =>
    typedError<boolean, LlmError>(__TAURI_INVOKE("clear_case_session", { caseId })),
  copyCaseOutput: (caseId: string) =>
    typedError<string, LlmError>(__TAURI_INVOKE("copy_case_output", { caseId })),
  createCaseSession: (id: string, templateId: string) =>
    typedError<CaseSession, LlmError>(
      __TAURI_INVOKE("create_case_session", { id, templateId }),
    ),
  extractFile: (fileName: string, bytes: number[]) =>
    typedError<ExtractedBlock, IngestError>(
      __TAURI_INVOKE("extract_file", { fileName, bytes }),
    ),
  extractRawText: (text: string) =>
    typedError<ExtractedBlock, IngestError>(
      __TAURI_INVOKE("extract_raw_text", { text }),
    ),
  extractTextFile: (fileName: string, bytes: number[]) =>
    typedError<ExtractedBlock, IngestError>(
      __TAURI_INVOKE("extract_text_file", { fileName, bytes }),
    ),
  generate: (request: GenerateRequest) =>
    typedError<null, LlmError>(__TAURI_INVOKE("generate", { request })),
  greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
  listModels: (profile: ProviderProfile) =>
    typedError<string[], LlmError>(__TAURI_INVOKE("list_models", { profile })),
  renderTemplateSystemPrompt: (
    template: ClinicalTemplate,
    values: { [key in string]: TemplateValue },
    enabledSectionIds: string[],
  ) =>
    typedError<string, TemplateError>(
      __TAURI_INVOKE("render_template_system_prompt", {
        template,
        values,
        enabledSectionIds,
      }),
    ),
  setCaseReview: (caseId: string, reviewed: boolean) =>
    typedError<boolean, LlmError>(
      __TAURI_INVOKE("set_case_review", { caseId, reviewed }),
    ),
  testProvider: (profile: ProviderProfile) =>
    typedError<null, LlmError>(__TAURI_INVOKE("test_provider", { profile })),
  validateTemplate: (bytes: number[]) =>
    typedError<ClinicalTemplate, TemplateError>(
      __TAURI_INVOKE("validate_template", { bytes }),
    ),
};

/** Events */
export const events = {
  generationDelta: makeEvent<GenerationDelta>("generation://delta"),
  generationDone: makeEvent<GenerationDone>("generation://done"),
  generationError: makeEvent<GenerationError>("generation://error"),
};

/* Types */
export type AuthSource =
  { source: "none" } | { source: "keychain"; credential_id: string };

export type CaseSession = {
  id: string;
  template_id: string;
  inputs: ExtractedBlock[];
  current_output: string | null;
  reviewed_output_hash: string | null;
};

export type ClinicalTemplate = {
  schema_version: number;
  metadata: TemplateMetadata;
  system_prompt: string;
  variables: TemplateVariable[];
  sections: TemplateSection[];
  output_rules?: OutputRules;
};

export type ExtractedBlock = {
  id: string;
  round: number;
  provenance: InputProvenance;
  content: string;
};

export type GenerateRequest = {
  requestId: string;
  caseId: string;
  profile: ProviderProfile;
  systemPrompt: string;
  outputRules: OutputRules;
  input: ExtractedBlock | null;
  corrections: string | null;
};

export type GenerationDelta = {
  requestId: string;
  content: string;
};

export type GenerationDone = {
  requestId: string;
  content: string;
  violations: OutputViolation[];
};

export type GenerationError = {
  requestId: string;
  error: LlmError;
};

export type GenerationParams = {
  temperature: number | null;
  max_tokens: number | null;
};

export type IngestError =
  | { key: "empty_input" }
  | { key: "invalid_utf8" }
  | { key: "unsupported_binary"; mime: string }
  | { key: "unsupported_control_characters" }
  | { key: "pdf_extraction_failed" }
  | { key: "no_text_extracted" }
  | { key: "pdf_ocr_required"; pages: number[] }
  | { key: "pdf_ocr_unavailable" }
  | { key: "pdf_ocr_failed" }
  | { key: "invalid_docx_archive" }
  | { key: "missing_docx_document" }
  | { key: "docx_document_too_large" }
  | { key: "invalid_docx_xml" }
  | { key: "invalid_xlsx" }
  | { key: "no_xlsx_worksheets" }
  | { key: "no_xlsx_text" }
  | { key: "html_conversion_failed" }
  | { key: "no_html_text" }
  | { key: "invalid_rtf" }
  | { key: "no_rtf_text" };

export type InputProvenance =
  | "RawText"
  | ({
      File: {
        name: string;
      };
    } & { Url?: never })
  | "Clipboard"
  | ({
      Url: {
        address: string;
      };
    } & { File?: never });

export type LlmError =
  | { key: "invalid_profile" }
  | { key: "invalid_request" }
  | { key: "authentication" }
  | { key: "network" }
  | { key: "model" }
  | { key: "quota" }
  | { key: "cancelled" }
  | { key: "internal" };

export type ModelCapabilities = {
  vision: boolean;
  streaming: boolean;
  max_context: number | null;
};

export type OutputRules = {
  forbidden_terms?: string[];
  required_terms?: string[];
  forbid_code_fences?: boolean;
  forbid_leading_whitespace?: boolean;
};

export type OutputViolation = {
  line: number;
  kind: OutputViolationKind;
  term: string | null;
};

export type OutputViolationKind =
  | "forbidden_term"
  | "missing_required_term"
  | "code_fence"
  | "leading_whitespace"
  | "parenthesized_date"
  | "bullet_character";

export type ProviderAdapter =
  "open_ai" | "anthropic" | "gemini" | "ollama" | "open_ai_compatible";

export type ProviderProfile = {
  id: string;
  display_name: string;
  adapter: ProviderAdapter;
  model: string;
  endpoint: string | null;
  auth: AuthSource;
  capabilities: ModelCapabilities;
  generation: GenerationParams;
};

export type TemplateDefault =
  { kind: "text"; value: string } | { kind: "boolean"; value: boolean };

export type TemplateError =
  | { key: "unsupported_schema_version"; value: number }
  | { key: "invalid_template" }
  | { key: "invalid_variable_name"; value: string }
  | { key: "duplicate_variable"; value: string }
  | { key: "invalid_variable_definition"; value: string }
  | { key: "invalid_section"; value: string }
  | { key: "invalid_section_selection" }
  | { key: "invalid_serialized_template" }
  | { key: "template_too_large" }
  | { key: "missing_required_variable"; value: string }
  | { key: "invalid_variable_value"; value: string }
  | { key: "unknown_variable"; value: string }
  | { key: "invalid_system_prompt" }
  | { key: "rendering_failed" };

export type TemplateMetadata = {
  id: string;
  name: string;
  description: string;
  locale: string;
  specialty_tags: string[];
  version: string;
  author: string;
};

export type TemplateSection = {
  id: string;
  heading: string;
  order: number;
  enabled_by_default: boolean;
  labels: { [key in string]: string };
};

export type TemplateValue = string | boolean;

export type TemplateVariable = {
  name: string;
  kind: TemplateVariableKind;
  labels: { [key in string]: string };
  default: TemplateDefault | null;
  required: boolean;
  options?: string[];
};

export type TemplateVariableKind = "text" | "select" | "boolean" | "date";

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>,
): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
  try {
    return { status: "ok", data: await result };
  } catch (e) {
    if (e instanceof Error) throw e;
    return { status: "error", error: e as any };
  }
}

type EventEmit<T> = [T] extends [null]
  ? () => Promise<void>
  : (payload: T) => Promise<void>;

function makeEvent<T>(
  name: string,
  serialize?: (payload: T) => unknown,
  deserialize?: (payload: any) => T,
) {
  const mapEvent =
    (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) =>
      cb({
        ...event,
        payload: deserialize ? deserialize(event.payload) : event.payload,
      });
  const mapPayload = (payload: T) => (serialize ? serialize(payload) : payload);

  const base = {
    listen: (cb: __TAURI_EVENT.EventCallback<T>) =>
      __TAURI_EVENT.listen(name, mapEvent(cb)),
    once: (cb: __TAURI_EVENT.EventCallback<T>) =>
      __TAURI_EVENT.once(name, mapEvent(cb)),
    emit: ((payload: T) =>
      __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
  };

  const fn = (
    target:
      | import("@tauri-apps/api/webview").Webview
      | import("@tauri-apps/api/window").Window,
  ) => ({
    listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
    once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
    emit: ((payload: T) =>
      target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
  });

  return Object.assign(fn, base);
}
